### ISSUE TITLE
logban working from <@id> tag

### ISSUE THREAD

**Issue by dashwav** [dashwav/yin-bot#4]
For consistency this would be nice to work the same way as an actual ban. Not sure how to implement exactly as the entire premise of the ban is that the member is not in the guild, so searching that way will not work.

**Comment by nickalaskreynolds** [comment]
So I have been thinking about this. I think there are 2 ways to go about this.
We either write our own side module to supplement discord.py so that it properly calls the discord API so we can modify the banlist directly, or, we have the bot store the ban list locally and then if a user that joins is in that list, it then issues the command to ban them server side. We could even have this check on every message (might get cumbersome IDK though) and auto issue bans as needed.

For the former, it would be "pretty simple" via sending the correct response <https://discordapp.com/developers/docs/resources/guild#create-guild-ban>

For the latter, it is also fairly simple. Just need to make sure the bot periodically pulls the server side ban list and add any new members to the bot ban list (just incase bot goes down). Then any time add_member_ban is fired (or new_message) then it just checks the userID against the bot ban list and if the user is a part of that list, it will then issue the server side ban.

**Comment by dashwav** [comment]
Hmmm the way I had maybe imagined it was checking to see if there is the string `<@1234512345>` and grab the id from that string and continue to run like normal.

**Comment by nickalaskreynolds** [comment]
not sure if this is worth a pull request.
In `cogs/moderation.py` I changed line 32 from `async def convert(self, ctx, argument): ` to `async def convert(self, ctx, argument: MemberID): `
I am new to these function annotations, but if I understand it correctly, this will send the argument through your class decorator MemberID which will try to serve the correct str/int. This class actually should take care of <@ID> cases for us and ID is already checked. So I think that will cover it
